<div class='main-container-plain' id='press'>
  <div class='container'>
  <h2 class='spaced'>Josh Knowles - EPK Spring 2020</h2>
    <hr />
    <div class='column-left'>
      <img class='press-img spaced' src='https://i.imgur.com/LKHbdLD.png' />
      
      <h3 class='bold spaced'>Artist Information</h3>
      <hr />
      <p class='strip'><span class='bold'>Label: </span>Independent</p>
      <p class='strip'><span class='bold'>Genre: </span>Indie/Indie Pop/Folktronica</p>
      <p class='strip'><span class='bold'>Hometown: </span>Boston, MA</p>
      <p class='strip'><span class='bold'>For Fans Of: </span>James Blake, Sylvan Esso, Bon Iver</p>

      <h3 class='bold spaced'>Biography</h3>
      <hr />
      <p>Josh Knowles is an electric violinist, singer/songwriter, and composer based in Boston, MA. He brings an eclectic array of influences to his original work, continually striving to fuse his traditional foundation with modern songwriting, experimental studio production, and stunning live performances.</p>
      <p>An in-demand and versatile musician, Knowles has featured on albums by <span class='bold'>The Front Bottoms</span>, <span class='bold'>John Nolan</span> (Taking Back Sunday), and <span class='bold'>An Horse</span>, performed on stages for <span class='bold'>Barack Obama</span>, <span class='bold'>David Letterman</span> and <span class='bold'>James Taylor</span>, and frequently collaborates with <span class='bold'>Cirio Collective</span> and <span class='bold'>Boston Ballet</span>, with whom he has appeared on stage for historic runs at the Boston Opera House and the Lincoln Center in New York. He currently resides as a Community Luminary at the Isabella Stewart Gardner Museum, where he performs regularly.</p>
      <p>In February of 2018, Knowles released "Spin Without A Sound," his debut instrumental album of loop-based ethereal solo electric violin pieces.</p>
      <p>In summer 2019 he showcased his songwriting side with debut breakthrough single "Same," which incorporated his signature electric violin tones but also showcased his prowess as a songwriter and vocalist. A unique and cathartic ballad, "Same" has garnered nearly 100,000 plays on Spotify.</p>
      <p>In early 2020, Knowles premiered a collection of new original material by performing it live on stage during a 3 night run with Providence Festival Ballet. His powerful experimental song and upcoming single “How Deep the Dark” opened the show, and will be released everywhere on May 26, 2020.</p>

      <h3 class='bold spaced'>Links</h3>
      <hr />
      <p class='strip'><span class='bold'>Website: </span><a class='link' href='https://www.joshknowlesmusic.com/' target='_blank'>https://www.joshknowlesmusic.com/</a></p>
      <p class='strip'><span class='bold'>Facebook: </span><a class='link' href='https://facebook.com/joshknowlesmusic' target='_blank'>https://www.facebook.com/joshknowlesmusic</a></p>
      <p class='strip'><span class='bold'>Instagram: </span><a class='link' href='https://instagram.com/joshknowlesmusic' target='_blank'>@joshknowlesmusic</a></p>
      <p class='strip'><span class='bold'>YouTube: </span><a class='link' href='https://www.youtube.com/channel/UCRiNextM-ExZS7S3qGNTxbw' target='_blank'>​Josh Knowles on YouTube</a></p>
      <p class='strip'><span class='bold'>Spotify: </span><a class='link' href='https://open.spotify.com/artist/2cYJgCe7KbXn1Y4TL0JCrK' target='_blank'>Josh Knowles on Spotify</a></p>
      <p class='strip'><span class='bold'>Apple Music/iTunes: </span><a class='link' href='https://music.apple.com/us/artist/josh-knowles/635148421' target='_blank'>J​osh Knowles on Apple Music</a></p>
      <p class='strip'><span class='bold'>Bandcamp: </span><a class='link' href='https://joshknowles.bandcamp.com' target='_blank'>Josh Knowles on Bandcamp</a></p>
    </div>

    <div class='column-right'>
      <div class='press-links'>
        <h3 class='bold spaced'>Press</h3>
        <hr />
        <p class='italic'>"Josh uses his skills with an electric violin to craft evocative string music that stimulates the heart and mind with each swell and beautiful cadence." -<a href='http://newengland.thedelimagazine.com/43477/deli-premiere-step-back-from-wrong-direction-by-josh-knowles' class='link' target='_blank'>The Deli Magazine</a></p>
        <p class='italic'>“Soothing melodies brought to powerful climaxes generated by way of an array of electronic effects: looped string tracks mixed together on-stage” -<a href='https://artsfuse.org/171606/theater-music-review-ruby-rose-fox-remembrance-of-musical-protests-past/' class='link' target='_blank'>ArtsFuse</a></p>
        <p class='italic'>“He plucks...he bows, he loops. Josh Knowles uses the entire musical arsenal of the violin. And he sings...a pop music voice, rich with great range, especially suited to enter a quiet room on a rich, warm violin music bed.” -<a href='https://geoffwilburmusic.com/tag/josh-knowles/' class='link' target='_blank'>Geoff Wilbur Music</a></p>
        <p class='strip'><a class='link' href='https://vanyaland.com/2018/04/13/josh-knowles-tweaks-instrumental-bliss-debut-solo-album/' target="_blank"><span class='bold'>April 2018</span> - Vanyaland - Josh Knowles Tweaks his Instrumental Bliss (Feature)</a></p>
        <p class='strip'><a class='link' href='http://www.bostonsurvivalguide.net/wordpress/2018/04/josh-knowles-weaves-violin-magic-on-spin-without-a-sound/' target="_blank"><span class='bold'>April 2018</span>​ - Boston Survival Guide - Josh Knowles Weaves Violin Magic (Feature)</a></p>
        <p class='strip'><a class='link' href='https://geoffwilburmusic.com/2018/04/01/behind-the-songs-2/' target="_blank"><span class='bold'>April 2018</span> - Geoff Wilbur Music - Hard Rock Cafe Behind the Songs Review</a></p>
        <p class='strip'><a class='link' href='https://ihrtn.net/watch-josh-knowles-great-blue-world/' target="_blank"><span class='bold'>May 2018</span>​ - I Heart Noise - “Great Blue World” (Video Feature)</a></p>
        <p class='strip'><a class='link' href='https://artsfuse.org/171606/theater-music-review-ruby-rose-fox-remembrance-of-musical-protests-past/' target="_blank"><span class='bold'>June 2018</span>​ - The Arts Fuse - Oberon Theater Concert Review</a></p>
        <p class='strip'><a class='link' href='https://ihrtn.net/show-review-love-chastity-and-death-josh-knowles-at-the-isabella-stewart-gardner-museum-08-09-18/2/' target="_blank"><span class='bold'>August 2018</span> - I Heart Noise - ISGM Calderwood Hall Concert Review</a></p>
        <p class='strip'><a class='link' href='https://www.bostonmagazine.com/arts-entertainment/2019/04/26/boston-ballet-dancers-music-video-josh-knowles/' target="_blank"><span class='bold'>April 2019</span>​ - Boston Magazine - "Same" (Writeup)</a></p>
        <p class='strip'><a class='link' href='https://www.pointemagazine.com/dont-miss-boston-ballets-lia-cirio-and-paul-craig-in-this-new-music-video-2635415909.html' target="_blank"><span class='bold'>April 2019</span> - Pointe Magazine - “Same” (Premiere)</a></p>
        <p class='strip'><a class='link' href='https://stringsmagazine.com/violinist-josh-knowles-on-his-new-music-video-ethereal-violin-sound/' target="_blank"><span class='bold'>May 2019</span> - Strings Magazine Feature</a>​</p>
        <p class='strip'><a class='link' href='https://www.boston.com/culture/music/2019/05/09/watch-boston-ballet-dancers-duet-in-this-electric-violinists-music-video' target="_blank"><span class='bold'>May 2019</span>​ - Boston.com - “Same” (Writeup)</a></p>
        <p class='strip'><a class='link' href='https://www.providencejournal.com/entertainmentlife/20200205/festival-ballet-providence-breaks-new-ground-with-innovative-edgy-game-changers' target="_blank"><span class='bold'>February 2020</span>​ - Providence Journal - Festival Ballet (Writeup)</a></p>
        <p class='strip'><a class='link' href='https://www.pointemagazine.com/lia-cirio-paul-craig-video-2645736970.html?rebelltitem=2%23rebelltitem2' target="_blank"><span class='bold'>March 2020</span>​ - Pointe Magazine - “Reverie” (Writeup)</a></p>
      </div>

      <h3 class='bold spaced'>Videos</h3>
      <hr />

      <img class='videos-image' src='https://i.imgur.com/x9SrI1i.png' />
      <p><a href='https://youtu.be/_drI0UGkKZg' class='link' target='_blank'>Same - Official Music Video (Feat. Boston Ballet Dancers)</a></p>

      <img class='videos-image' src='https://i.imgur.com/Q2WymHo.png' />
      <p><a href='https://youtu.be/92P4t0kXL0Y' class='link' target='_blank'>Ember - Live Loop Performance</a></p>

      <img class='videos-image' src='https://i.imgur.com/HhRsNlH.png' />
      <p><a href='https://www.youtube.com/watch?v=fSD5CPvRc-Q' class='link' target='_blank'>Thrown Stone - Official Music Video</a></p>

      <h3 class='bold spaced'>Contact</h3>
      <hr />

      <p class='strip'><span class='bold'>Josh Knowles</span></p>
      <p class='strip'><span class='bold'>Email: </span><a class='link' href='mailto:jaknowles320@gmail.com'>​jaknowles320@gmail.com</a></p>
      <p class='strip'><span class='bold'>Phone: </span>​857-636-1963</p>

      <div class='spaced' />
      <p class='strip'><span class='bold'>Alex Glover</span> - <span class='italic'>Booking / Management / Information</span></p>
      <p class='strip'><span class='bold'>Email: </span><a class='link' href='mailto:alex@birdlabrecords.com'>alex@birdlabrecords.com</a></p>
      <p class='strip'><span class='bold'>Phone: </span>516-510-0500</p>
    </div>
    <div class="clear"></div>
  </div>
</div>

<style>
  .main-container-plain {
    background-color: white;
  }

  #press {
    padding-bottom: 100px;
    position: relative;
  }

  #press p {
    font-size: 13px;
  }

  .column-left {
    width: 47%;
    max-width: 450px;
    float: left;
  }

  .column-right {
    margin-left: calc(47% + 50px);
    width: 47%;
    max-width: 450px;
  }

  .press-img {
    width: 100%;
    max-width: 450px;
  }

  .spaced {
    padding-top: 15px;
  }

  .bold {
    font-weight: bolder !important;
  }

  .italic {
    font-style: italic;
  }

  a:hover {
    text-decoration: underline
  }

  .clear {
    clear: both
  }

  .videos-image {
    display: block;
    width: 300px;
  }

  .container {
    width: 90%;
    max-width: 1000px;
    display: block;
    position: relative;
    margin: 0 auto;
  }

  .column-left {
    width: 47%;
    max-width: 450px;
    float: left;
  }

  .column-right {
    margin-left: calc(47% + 50px);
    width: 47%;
    max-width: 450px;
  }

  @media (max-width: 600px) {
    .column-left {
      width: 100%;
      max-width: none;
      float: none;
    }

    .column-right {
      width: 100%;
      max-width: none;
      float: none;
      margin-left: 0;
    }
  }
</style>